apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientserver-service
spec:
  selector:
    matchLabels:
      app: clientserver-app
  replicas: 1
  template:
    metadata:
      labels:
        app: clientserver-app
    spec:
      containers:
        - image: client-service
          name: clientserver-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: clientserver-app