apiVersion: apps/v1
kind: Deployment
metadata:
  name: excursionserver-service
spec:
  selector:
    matchLabels:
      app: excursionserver-app
  replicas: 1
  template:
    metadata:
      labels:
        app: excursionserver-app
    spec:
      containers:
        - image: excursion-service
          name: excursionserver-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: excursion-service
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
  selector:
    app: excursionserver-app