apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupserver-service
spec:
  selector:
    matchLabels:
      app: groupserver-app
  replicas: 1
  template:
    metadata:
      labels:
        app: groupserver-app
    spec:
      containers:
        - image: group-service
          name: groupserver-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: group-service
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: groupserver-app