apiVersion: apps/v1
kind: Deployment
metadata:
  name: guideserver-service
spec:
  selector:
    matchLabels:
      app: guideserver-app
  replicas: 1
  template:
    metadata:
      labels:
        app: guideserver-app
    spec:
      containers:
        - image: guide-service
          name: guideserver-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: guide-service
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app: guideserver-app