apiVersion: apps/v1
kind: Deployment
metadata:
  name: managerserver-service
spec:
  selector:
    matchLabels:
      app: managerserver-app
  replicas: 1
  template:
    metadata:
      labels:
        app: managerserver-app
    spec:
      containers:
        - image: manager-service
          name: managerserver-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: manager-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: managerserver-app