apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-service
spec:
  selector:
    matchLabels:
      app: server-app
  replicas: 1
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - image: server-app
          name: serverserver-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer
  ports:
    - port: 8087
      protocol: TCP
      targetPort: 8087
  selector:
    app: server-app